<a href="https://colab.research.google.com/github/skarchana-ai/Machine-Learning/blob/main/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Feature Engineering

Step 1: Missing-Value Handling

In [9]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [4]:
data={
    "Name":["Akhil","Rahul","Anu","Meera","John"],
    "Age":[20,None,22,21,None],
    "Marks":[85,90,None,75,80],
    "City":["Kochi","Calicut",None,"Kochi","Calicut"]

}

In [5]:
df=pd.DataFrame(data)

In [6]:
df

    Name   Age  Marks     City
0  Akhil  20.0   85.0    Kochi
1  Rahul   NaN   90.0  Calicut
2    Anu  22.0    NaN     None
3  Meera  21.0   75.0    Kochi
4   John   NaN   80.0  Calicut

Check missing values in each column

In [7]:
df.isnull().sum()

Name     0
Age      2
Marks    1
City     1
dtype: int64

Convert any python "None"or string"None"into actual mathematical NaN values

In [10]:
df["City"]=df["City"].replace(["None",None],np.nan)

In [11]:
df

    Name   Age  Marks     City
0  Akhil  20.0   85.0    Kochi
1  Rahul   NaN   90.0  Calicut
2    Anu  22.0    NaN      NaN
3  Meera  21.0   75.0    Kochi
4   John   NaN   80.0  Calicut

In [12]:
num_imputer=SimpleImputer(strategy='median')
df[["Age","Marks"]]=num_imputer.fit_transform(df[["Age","Marks"]])

cat_imputer=SimpleImputer(strategy="most_frequent")
df[["City"]]=cat_imputer.fit_transform(df[["City"]])

In [13]:
df

    Name   Age  Marks     City
0  Akhil  20.0   85.0    Kochi
1  Rahul  21.0   90.0  Calicut
2    Anu  22.0   82.5  Calicut
3  Meera  21.0   75.0    Kochi
4   John  21.0   80.0  Calicut